title: Ethical Design of Forensic Scripts
author: Team 3 – Fatima Iqbal, Brian Palencia Sanchez, Simran Kaur, Bryan Fayad Pirbaksh, Saiyad Mohamed Hussain
description: CYB 625 Final Project – Principles of Secure Scripting and Cryptography
theme: minima
markdown: kramdown

